version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install django-rest-assured
            sudo pip install -U pytest
            sudo pip install pytest-html
      - run:
          name: Running tests
          command: |
            pytest -sv --html report/report.html
      - store_artifacts:
          path: report/
          destination: python_app
      - run: |
          curl https://circleci.com/api/v1.1/project/github/cupidline/RestAssured_Python/latest/artifacts?circle-token=xoxp-246836257924-853166129012-895821502261-65c170fa090c0eb3744c345b9848205c

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 1 1 *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
